import student, group

st1 = student.Student('Male', 30, 'Steve', 'Jobs', '1')
st2 = student.Student('Female', 25, 'Liza', 'Taylor', '2')
st3 = student.Student("Male", 22, "Roman", "Strus", "3")
st4 = student.Student("Male", 22, "Roma", "Strus", "4")
st5 = student.Student("Male", 22, "Rom", "Strus", "5")
st6 = student.Student("Male", 22, "Ro", "Strus", "6")
st7 = student.Student("Male", 22, "R", "Strus", "7")
st8 = student.Student("Male", 22, "Roman", "Strus", "8")
st9 = student.Student("Male", 22, "Roman", "Stru", "9")
st10 = student.Student("Male", 22, "Roman", "Str", "10")
st11 = student.Student("Male", 22, "Roman", "St", "11")
gr = group.Group('PD1')
gr.add_student(st1)
gr.add_student(st2)
gr.add_student(st3)
gr.add_student(st4)
gr.add_student(st5)
gr.add_student(st6)
gr.add_student(st7)
gr.add_student(st8)
gr.add_student(st9)
gr.add_student(st10)
try:
    gr.add_student(st11)
except Exception as e:
    print(e)
print(gr)
print(gr.find_student('Jobs'))
print(gr.find_student('Jobs2'))
gr.delete_student('Jobs')
gr.delete_student('Jobs2')
print(gr)